### ISSUE TITLE
Missing transit_enable_active_standby for transit gateway submodule

### ISSUE THREAD

**Issue by pawelfraczyk** [terraform-aviatrix-modules/terraform-aviatrix-backbone#2]
Hello,

I can't enable active-standby on Transit Gateway.
Docs: https://docs.aviatrix.com/documentation/v7.0/building-your-network/bgp-connection-settings.html#active-standby

I see module has only:

transit_enable_active_standby_preemptive
Setting this option to 'true' will still show Terraform plan to keep value of enable_active_standby as false and fail to deploy. See attached screen.

![image](https://github.com/terraform-aviatrix-modules/terraform-aviatrix-backbone/assets/56155290/8527720e-fa32-48dd-ac5f-1d4c23076702)

Can you add this property e.g. transit_enable_active_standby to pass it down to the module of transit gateway?

Controller version: UserConnect-7.0.1768
Provider: 3.0.5

**Comment by Dennizz** [comment]
Please go ahead and test with v1.1.3 and let me know your results.

Kr,

Dennis

**Comment by pawelfraczyk** [comment]
It works perfect now!

Many thanks @Dennizz for quick fix! 🥇 🤝
