### ISSUE TITLE
Active_standby for Controller 7.1

### ISSUE THREAD

**Issue by fabianobianchi** [terraform-aviatrix-modules/terraform-aviatrix-backbone#5]
Hello!

In the issue https://github.com/terraform-aviatrix-modules/terraform-aviatrix-backbone/issues/2 it was fixed an issue providing a variable to enable the active_standby feature (transit_enable_active_standby), and we onboarded this option in version 1.1.3. However, I have updated the module version to 1.2.2 to keep compatibility with my new Controller version 7.1, and I noticed that this option is not available anymore.

Can you please double-check? I have a drift on my terraform plan

**Comment by Dennizz** [comment]
Hi Fabiano, for some reason the backport never made it to the 1.2.x train. I have just released version 1.2.4 that should address this. Can you please verify this resolves your issue?

**Comment by fabianobianchi** [comment]
Thank you so much @Dennizz ! After your changes, version 1.2.4 is working fine!

**Comment by fabianobianchi** [comment]
The issue was fixed in the release version 1.2.4
